project_name: generic-processor

before:
  hooks:
    - go mod tidy

builds:
  - main: ./generic-processor/
    binary: generic-processor
    ldflags:
      - -s -w -X main.build={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

dockers:
  - use: buildx
    dockerfile: ./build/package/Dockerfile
    image_templates:
      - "ghcr.io/hawkv6/generic-processor:latest"
      - "ghcr.io/hawkv6/generic-processor:{{ .Tag }}"