inputs:
  - influx:
    name: jalapeno-influx
    url: http://influxdb:8086
    db: mdt_db
    username: jalapeno
    password: jalapeno
  - kafka:
    name: jalapeno-kafka
    url: kafka:9092
    input_topic: openconfig

outputs:
  - arango:
    name: jalapeno-arango
    url: 
    database: jalapeno
    username: root
    password: jalapeno

processors:
  - ArangoDocumentCreater:
    input: jalapeno-kafka
    output: jalapeno-arango
    ouput_document: mdt.openconfig  
  - ArangoDocumentEnricher:
    interval: 30 # seconds
    input: jalapeno-influx
    output: jalapeno-arango
    modes:
      - methods: minimum
        input:
          measurement: performance-measurement
          filter_by: mdt.openconfig.name
          field: delay_measurement_session/last_advertisement_information/advertised_values/average
          group_by:
            - interval
            - mdt.openconfig.interface_name
            - mdt.openconfig.name
        output:
          document: ls_link
          filter_by:
            - mdt.openconfig.name
            - mdt.openconfig.ipv6_address
          field: unidir_link_delay