inputs:
  kafka:
    jalapeno-kafka-openconfig:
      broker: 10.8.39.68:9094
      topic: hawkv6.openconfig
  influx:
    jalapeno-influx:
      url: http://10.8.39.67:8086
      db: mdt_db
      username: jalapeno
      password: jalapeno

outputs:
  arango:
    jalapeno-arango:
      url: https://arango-hawkv6.stud.network.garden/
      database: jalapeno
      username: root
      password: jalapeno
  # kafka:
  #   jalapeno-kafka-lslink-events:
  #     broker: 172.16.19.77:9094
  #     topic: jalapeno.ls_node_edge_events


processors:
    TelemetryToArango:
      LsLink:
        inputs:
          - jalapeno-kafka-openconfig
          - jalapeno-influx
        outputs: 
          - jalapeno-arango
        #   - jalapeno-kafka-lslink-events
        interval: 30 # seconds
        modes:
          - input-options:
              jalapeno-influx:
                measurement: performance-measurement
                field: delay_measurement_session/last_advertisement_information/advertised_values/average
                method: mean
                group_by:
                  - interface_name
                  - source 
            output-options:
              jalapeno-arango:
                collection: ls_link
                method: update
                filter_by:
                  - local_link_ip
                field: unidir_link_delay
          - input-options:
              jalapeno-influx:
                measurement: performance-measurement
                field: delay_measurement_session/last_advertisement_information/advertised_values/minimum
                method: min
                group_by:
                  - interface_name
                  - source
            output-options:
              jalapeno-arango:
                collection: ls_link
                method: update
                filter_by:
                  - local_link_ip
                field: unidir_link_delay_min_max
                index: 0
          - input-options:
              jalapeno-influx:
                measurement: performance-measurement
                field: delay_measurement_session/last_advertisement_information/advertised_values/maximum
                method: max
                group_by:
                  - interface_name
                  - source
            output-options:
              jalapeno-arango:
                collection: ls_link
                method: update
                filter_by:
                  - local_link_ip
                field: unidir_link_delay_min_max
                index: 1
          # - input-options:
          #     jalapeno-influx:
          #       measurement: performance-measurement
          #       field: delay_measurement_session/last_advertisement_information/advertised_values/variance
          #       method: mean
          #       group_by:
          #         - interface_name
          #         - source
          #   output-options:
          #     jalapeno-arango:
          #       collection: ls_link
          #       method: update
          #       filter_by:
          #         - local_link_ip
          #       field: unidir_delay_variation
          # - input-options:
          #     jalapeno-influx:
          #       measurement: isis
          #       field: interface_status_and_data/enabled/packet_loss_percentage 
          #       method: max
          #       group_by:
          #         - interface_name
          #         - source
          #   output-options:
          #     jalapeno-arango:
          #       collection: ls_link
          #       method: update
          #       filter_by:
          #         - local_link_ip
          #       field: unidir_packet_loss
          # - input-options:
          #     jalapeno-influx:
          #       measurement: isis
          #       field: interface_status_and_data/enabled/packet_loss_percentage 
          #       method: max
          #       group_by:
          #         - interface_name
          #         - source
          #   output-options:
          #     jalapeno-arango:
          #       collection: ls_link
          #       method: update
          #       filter_by:
          #         - local_link_ip
          #       field: unidir_packet_loss
          # - input-options:
          #     jalapeno-influx:
          #       measurement: isis
          #       field: interface_status_and_data/enabled/bandwidth 
          #       method: last
          #       group_by:
          #         - interface_name
          #         - source
          #   output-options:
          #     jalapeno-arango:
          #       collection: ls_link
          #       method: update
          #       filter_by:
          #         - local_link_ip
          #       field: unidir_available_bw
          # - input-options:
          #     jalapeno-influx:
          #       measurement: utilization
          #       field: out_octets
          #       method: max
          #       group_by:
          #         - interface_name
          #         - source
          #   output-options:
          #     jalapeno-arango:
          #       collection: ls_link
          #       method: update
          #       filter_by:
          #         - local_link_ip
          #       field: unidir_bw_utilization